<?php
// Persian Language File
$lang = [
    // Navigation
    'dashboard' => 'داشبورد',
    'products' => 'اجناس',
    'categories' => 'دسته بندی ها',
    'customers' => 'مشتریان',
    'suppliers' => 'تأمین کنندگان',
    'sales' => 'فروش',
    'purchases' => 'خرید',
    'reports' => 'گزارشات',
    'users' => 'کاربران',
    'backup' => 'پشتیبان گیری',
    'settings' => 'تنظیمات',

    // Common
    'add' => 'افزودن',
    'edit' => 'ویرایش',
    'delete' => 'حذف',
    'save' => 'ذخیره',
    'cancel' => 'انصراف',
    'search' => 'جستجو',
    'view' => 'مشاهده',
    'print' => 'چاپ',
    'download' => 'دانلود',
    'excel' => 'اکسل',
    'total' => 'کل',
    'date' => 'تاریخ',
    'name' => 'نام',
    'phone' => 'تلفن',
    'address' => 'آدرس',
    'description' => 'توضیحات',
    'price' => 'قیمت',
    'quantity' => 'تعداد',
    'status' => 'وضعیت',
    'actions' => 'عملیات',

    // Dashboard
    'total_products' => 'کل اجناس',
    'total_customers' => 'کل مشتریان',
    'today_sales' => 'فروش امروز',
    'low_stock' => 'کم موجود',
    'sales_chart' => 'آمار فروش',
    'top_products' => 'اجناس پرفروش',

    // Products
    'product_management' => 'مدیریت اجناس',
    'new_product' => 'جنس جدید',
    'product_name' => 'نام جنس',
    'product_code' => 'کد جنس',
    'category' => 'دسته بندی',
    'buy_price' => 'قیمت خرید',
    'sell_price' => 'قیمت فروش',
    'stock_quantity' => 'موجودی',
    'min_stock' => 'حداقل موجودی',
    'available' => 'موجود',
    'low_stock_item' => 'کم موجود',
    'out_of_stock' => 'ناموجود',

    // Sales
    'sales_management' => 'مدیریت فروش',
    'new_invoice' => 'فاکتور جدید',
    'customer' => 'مشتری',
    'cash_customer' => 'مشتری نقدی',
    'discount' => 'تخفیف',
    'invoice_items' => 'بخش ها فاکتور',
    'unit_price' => 'قیمت واحد',
    'subtotal' => 'جمع',
    'total_amount' => 'مبلغ کل',
    'final_amount' => 'مبلغ نهایی',
    'submit_invoice' => 'ثبت فاکتور',

    // Users
    'user_management' => 'مدیریت کاربران',
    'new_user' => 'کاربر جدید',
    'username' => 'نام کاربری',
    'full_name' => 'نام کامل',
    'password' => 'رمز عبور',
    'role' => 'نقش',
    'admin' => 'مدیر',
    'manager' => 'مدیر فروش',
    'employee' => 'کارمند',
    'registration_date' => 'تاریخ ثبت',

    // Settings
    'system_settings' => 'تنظیمات سیستم',
    'shop_info' => 'اطلاعات فروشگاه',
    'shop_name' => 'نام فروشگاه',
    'shop_phone' => 'تلفن فروشگاه',
    'shop_address' => 'آدرس فروشگاه',
    'currency' => 'واحد پول',
    'language' => 'زبان',
    'date_format' => 'نوع تاریخ',
    'auto_backup' => 'پشتیبان گیری خودکار',
    'notifications' => 'اعلانات',
    'save_settings' => 'ذخیره تنظیمات',

    // Messages
    'success' => 'موفقیت',
    'error' => 'خطا',
    'saved_successfully' => 'با موفقیت ذخیره شد',
    'deleted_successfully' => 'با موفقیت حذف شد',
    'operation_failed' => 'عملیات ناموفق',
    'invalid_request' => 'درخواست نامعتبر',
    'access_denied' => 'دسترسی مجاز نیست',
    'confirm_delete' => 'آیا از حذف اطمینان دارید؟',

    // Backup
    'backup_management' => 'مدیریت پشتیبان گیری',
    'create_backup' => 'ایجاد پشتیبان',
    'backup_files' => 'فایلهای پشتیبان',
    'file_name' => 'نام فایل',
    'creation_date' => 'تاریخ ایجاد',
    'file_size' => 'حجم فایل',

    // Purchases
    'purchase_management' => 'مدیریت خرید',
    'new_purchase' => 'خرید جدید',
    'supplier' => 'تأمین کننده',
    'purchase_items' => 'بخش ها خرید',
    'new_product_option' => '+ جنس جدید',
    'new_product_name' => 'نام جنس جدید',
    'new_product_code' => 'کد جنس جدید',
    'select_category' => 'انتخاب دسته بندی',

    // Reports
    'reports_management' => 'مدیریت گزارشات',
    'sales_report' => 'گزارش فروش',
    'products_report' => 'گزارش اجناس',
    'customers_report' => 'گزارش مشتریان',

    // Currency
    'afghani' => 'افغانی',
    'toman' => 'افغانی',
    'rial' => 'ریال',

    // Forms
    'select_option' => 'انتخاب کنید',
    'required_fields' => 'فیلدهای الزامی',
    'optional' => 'اختیاری',
    'confirm' => 'تایید',
    'close' => 'بستن',
    'submit' => 'ارسال',
    'update' => 'بروزرسانی',
    'create' => 'ایجاد',
    'manage' => 'مدیریت',
    'list' => 'لیست',
    'details' => 'جزئیات',
    'information' => 'اطلاعات',
    'general' => 'عمومی',
    'advanced' => 'پیشرفته',
    'basic' => 'پایه',
    'all' => 'همه',
    'today' => 'امروز',
    'this_month' => 'این ماه',
    'completed' => 'تکمیل شده',
    'pending' => 'در انتظار',
    'active' => 'فعال',
    'inactive' => 'غیرفعال',
    'yes' => 'بله',
    'no' => 'خیر',
    'enabled' => 'فعال',
    'disabled' => 'غیرفعال',
    'public' => 'عمومی',
    'private' => 'خصوصی',
    'system_operations' => 'عملیات سیستم',
    'shop_management' => 'مدیریت فروشگاه',
    'motorcycle_parts_shop' => 'فروشگاه قطعات',

    // Additional translations
    'from_last_month' => 'از ماه گذشته',
    'from_last_week' => 'از هفته گذشته',
    'from_yesterday' => 'از دیروز',
    'overview' => 'نمای کلی',
    'performance' => 'عملکرد',
    'latest_activities' => 'آخرین فعالیت ها',
    'activity' => 'فعالیت',
    'amount' => 'مبلغ',
    'new_sale' => 'فروش جدید',
    'cash' => 'نقدی',
    'available_stock' => 'موجود',
    'select_product' => 'انتخاب جنس',
    'add_row' => 'افزودن ردیف',
    'remove' => 'حذف',
    'invoice_number' => 'شماره فاکتور',
    'supplier_name' => 'نام تأمین کننده',
    'creation_date' => 'تاریخ ایجاد',
    'operations' => 'عملیات',
    'view_details' => 'مشاهده جزئیات',
    'print_invoice' => 'چاپ فاکتور',
    'download_pdf' => 'دانلود PDF',
    'export' => 'خروجی',
    'import' => 'ورودی',
    'backup_created' => 'پشتیبان ایجاد شد',
    'create_new_backup' => 'ایجاد پشتیبان جدید',
    'system_statistics' => 'آمار سیستم',
    'general_settings' => 'تنظیمات عمومی',
    'shop_information' => 'اطلاعات فروشگاه',
    'system_language' => 'زبان سیستم',
    'date_type' => 'نوع تاریخ',
    'gregorian' => 'میلادی',
    'jalali' => 'هجری شمسی',
    'automatic_backup' => 'پشتیبان گیری خودکار',
    'system_notifications' => 'اعلانات سیستم',
    'save_changes' => 'ذخیره تغییرات',

    // More translations
    'code' => 'کد',
    'stock' => 'موجودی',
    'afghani_currency' => 'افغانی',
    'previous' => 'قبلی',
    'next' => 'بعدی',
    'current' => 'فعلی',
    'all_tab' => 'همه',
    'today_tab' => 'امروز',
    'this_month_tab' => 'این ماه',
    'invoice' => 'فاکتور',
    'customer_name' => 'نام مشتری',
    'total_amount_label' => 'مبلغ کل',
    'discount_label' => 'تخفیف',
    'final_amount_label' => 'مبلغ نهایی',
    'date_label' => 'تاریخ',
    'status_label' => 'وضعیت',
    'actions_label' => 'عملیات',
    'print_invoice_action' => 'چاپ فاکتور',
    'view_details_action' => 'مشاهده جزئیات',
    'download_pdf_action' => 'دانلود PDF',
    'customer_label' => 'مشتری',
    'discount_input' => 'تخفیف',
    'invoice_items_label' => 'بخش ها فاکتور',
    'product_label' => 'جنس',
    'quantity_label' => 'تعداد',
    'unit_price_label' => 'قیمت واحد',
    'sum_label' => 'جمع',
    'operations_label' => 'عملیات',
    'add_item' => 'افزودن آیتم',
    'calculator' => 'ماشین حساب',
    'money_bill' => 'اسکناس',
    'cancel_button' => 'انصراف',
    'submit_invoice_button' => 'ثبت فاکتور',

    // Categories
    'category_management' => 'مدیریت دسته بندی ها',
    'new_category' => 'دسته بندی جدید',
    'category_name' => 'نام دسته بندی',
    'category_description' => 'توضیحات دسته بندی',

    // Customers
    'customer_management' => 'مدیریت مشتریان',
    'new_customer' => 'مشتری جدید',
    'customer_phone' => 'تلفن مشتری',
    'customer_address' => 'آدرس مشتری',

    // Suppliers
    'supplier_management' => 'مدیریت تأمین کنندگان',
    'new_supplier' => 'تأمین کننده جدید',
    'supplier_phone' => 'تلفن تأمین کننده',
    'supplier_address' => 'آدرس تأمین کننده',

    // Purchases
    'purchase_invoice' => 'فاکتور خرید',
    'purchase_date' => 'تاریخ خرید',
    'purchase_total' => 'کل خرید',

    // Reports
    'reports_title' => 'گزارشات',
    'sales_reports' => 'گزارشات فروش',
    'product_reports' => 'گزارشات اجناس',
    'customer_reports' => 'گزارشات مشتریان',

    // Login
    'login_title' => 'ورود به سیستم',
    'username_label' => 'نام کاربری',
    'password_label' => 'رمز عبور',
    'login_button' => 'ورود',
    'remember_me' => 'مرا به خاطر بسپار',

    // Profile
    'profile_title' => 'پروفایل کاربری',
    'change_password' => 'تغییر رمز عبور',
    'current_password' => 'رمز عبور فعلی',
    'new_password' => 'رمز عبور جدید',
    'confirm_password' => 'تایید رمز عبور',

    // Common form elements
    'required_field' => 'الزامی',
    'optional_field' => 'اختیاری',
    'select_category' => 'انتخاب دسته بندی',
    'select_customer' => 'انتخاب مشتری',
    'select_supplier' => 'انتخاب تأمین کننده',
    'list_title' => 'لیست',
    'add_new' => 'افزودن جدید',
    'edit_item' => 'ویرایش',
    'delete_item' => 'حذف',
    'view_item' => 'مشاهده',

    // Complete translations for all remaining texts
    'welcome' => 'خوش آمدید',
    'login_with_credentials' => 'ورود با اطلاعات کاربری',
    'or_login_with' => 'یا با اطلاعات کاربری وارد شوید',
    'forgot_password' => 'فراموشی رمز عبور؟',
    'about_us' => 'درباره ما',
    'blog' => 'وبلاگ',
    'licenses' => 'مجوزها',
    'facebook' => 'فیسبوک',
    'google' => 'گوگل',
    'error_exclamation' => 'خطا!',
    'wrong_credentials' => 'نام کاربری یا رمز عبور اشتباه است',
    'invalid_request' => 'درخواست نامعتبر',
    'chart' => 'نمودار',
    'daily_sales' => 'فروش روزانه',
    'last_30_days' => '(30 روز گذشته)',
    'invoice_count' => 'تعداد فاکتور',
    'total_sales' => 'مجموع فروش',
    'sold_quantity' => 'تعداد فروخته شده',
    'total_revenue' => 'کل درآمد',
    'stock_quantity' => 'مقدار موجودی',
    'toman' => 'افغانی',
    'search_placeholder' => 'جستجو...',
    'no_data' => 'اطلاعاتی موجود نیست',
    'loading' => 'در حال بارگذاری',
    'success_operation' => 'عملیات با موفقیت انجام شد',
    'operation_error' => 'خطا در انجام عملیات',
    'server_error' => 'خطا در ارتباط با سرور',
    'confirm_delete_question' => 'آیا از حذف اطمینان دارید؟',
    'successfully_deleted' => 'با موفقیت حذف شد',
    'delete_error' => 'خطا در حذف',
    'add_new_item' => 'افزودن آیتم جدید',
    'edit_title' => 'ویرایش',
    'update_button' => 'بروزرسانی',
    'new_password_optional' => 'رمز عبور جدید (اختیاری)',
    'system_title' => 'سیستم مدیریت فروشگاه قطعات موتورسیکلت',
    'contact_number' => 'شماره تماس',
    'main_street' => 'خیابان اصلی',
    'plate_number' => 'پلاک',
    'currency_unit' => 'واحد پول',
    'system_language_label' => 'زبان سیستم',
    'persian' => 'فارسی',
    'pashto' => 'پشتو',
    'english' => 'انگلیسی',
    'date_format_label' => 'نوع تاریخ',
    'solar_hijri' => 'هجری شمسی',
    'settings_updated' => 'تنظیمات با موفقیت بروزرسانی شد',
    'settings_update_error' => 'خطا در بروزرسانی تنظیمات'
];
?>