<?php
// Pashto Language File
$lang = [
    // Navigation
    'dashboard' => 'کورپاڼه',
    'products' => 'توکي',
    'categories' => 'ډولونه',
    'customers' => 'پیرودونکي',
    'suppliers' => 'چمتو کوونکي',
    'sales' => 'پلورنه',
    'purchases' => 'پیرودنه',
    'reports' => 'راپورونه',
    'users' => 'کاروونکي',
    'backup' => 'بیک اپ',
    'settings' => 'تنظیمات',

    // Common
    'add' => 'اضافه کول',
    'edit' => 'سمون',
    'delete' => 'ړنګول',
    'save' => 'ساتل',
    'cancel' => 'لغوه کول',
    'search' => 'لټون',
    'view' => 'کتل',
    'print' => 'چاپ',
    'download' => 'ډاونلوډ',
    'excel' => 'اکسل',
    'total' => 'ټول',
    'date' => 'نیټه',
    'name' => 'نوم',
    'phone' => 'تلیفون',
    'address' => 'پته',
    'description' => 'تشریح',
    'price' => 'بیه',
    'quantity' => 'مقدار',
    'status' => 'حالت',
    'actions' => 'عملیات',

    // Dashboard
    'total_products' => 'ټول توکي',
    'total_customers' => 'ټول پیرودونکي',
    'today_sales' => 'نن پلورنه',
    'low_stock' => 'لږ موجود',
    'sales_chart' => 'د پلورنې چارټ',
    'top_products' => 'غوره توکي',

    // Products
    'product_management' => 'د توکو مدیریت',
    'new_product' => 'نوی توکی',
    'product_name' => 'د توکي نوم',
    'product_code' => 'د توکي کوډ',
    'category' => 'ډول',
    'buy_price' => 'د پیرودنې بیه',
    'sell_price' => 'د پلورنې بیه',
    'stock_quantity' => 'موجود مقدار',
    'min_stock' => 'لږترین موجود',
    'available' => 'موجود',
    'low_stock_item' => 'لږ موجود',
    'out_of_stock' => 'نشته',

    // Sales
    'sales_management' => 'د پلورنې مدیریت',
    'new_invoice' => 'نوی فاکتور',
    'customer' => 'پیرودونکی',
    'cash_customer' => 'نغدي پیرودونکی',
    'discount' => 'تخفیف',
    'invoice_items' => 'د فاکتور توکي',
    'unit_price' => 'د واحد بیه',
    'subtotal' => 'برخه ټول',
    'total_amount' => 'ټول مقدار',
    'final_amount' => 'وروستی مقدار',
    'submit_invoice' => 'فاکتور ثبت کول',

    // Users
    'user_management' => 'د کاروونکو مدیریت',
    'new_user' => 'نوی کاروونکی',
    'username' => 'د کاروونکي نوم',
    'full_name' => 'بشپړ نوم',
    'password' => 'پټنوم',
    'role' => 'رول',
    'admin' => 'مدیر',
    'manager' => 'د پلورنې مدیر',
    'employee' => 'کارمند',
    'registration_date' => 'د ثبت نیټه',

    // Settings
    'system_settings' => 'د سیسټم تنظیمات',
    'shop_info' => 'د پلورنځي معلومات',
    'shop_name' => 'د پلورنځي نوم',
    'shop_phone' => 'د پلورنځي تلیفون',
    'shop_address' => 'د پلورنځي پته',
    'currency' => 'د پیسو واحد',
    'language' => 'ژبه',
    'date_format' => 'د نیټې ډول',
    'auto_backup' => 'اتوماتیک بیک اپ',
    'notifications' => 'خبرتیاوې',
    'save_settings' => 'تنظیمات ساتل',

    // Messages
    'success' => 'بریالیتوب',
    'error' => 'تیروتنه',
    'saved_successfully' => 'په بریالیتوب سره وساتل شو',
    'deleted_successfully' => 'په بریالیتوب سره وړنګول شو',
    'operation_failed' => 'عملیات ناکام شو',
    'invalid_request' => 'غلط غوښتنه',
    'access_denied' => 'لاسرسی منع',
    'confirm_delete' => 'ایا تاسو د ړنګولو څخه ډاډه یاست؟',

    // Backup
    'backup_management' => 'د بیک اپ مدیریت',
    'create_backup' => 'بیک اپ جوړول',
    'backup_files' => 'د بیک اپ فایلونه',
    'file_name' => 'د فایل نوم',
    'creation_date' => 'د جوړولو نیټه',
    'file_size' => 'د فایل اندازه',

    // Purchases
    'purchase_management' => 'د پیرودنې مدیریت',
    'new_purchase' => 'نوی پیرود',
    'supplier' => 'چمتو کوونکی',
    'purchase_items' => 'د پیرود توکي',
    'new_product_option' => '+ نوی توکی',
    'new_product_name' => 'د نوي توکي نوم',
    'new_product_code' => 'د نوي توکي کوډ',
    'select_category' => 'ډول غوره کړئ',

    // Reports
    'reports_management' => 'د راپورونو مدیریت',
    'sales_report' => 'د پلورنې راپور',
    'products_report' => 'د توکو راپور',
    'customers_report' => 'د پیرودونکو راپور',

    // Currency
    'afghani' => 'افغانۍ',
    'toman' => 'تومان',
    'rial' => 'ریال',

    // Forms
    'select_option' => 'غوره کړئ',
    'required_fields' => 'ټول ډکونه اړین دي',
    'optional' => 'اختیاري',
    'confirm' => 'تایید',
    'close' => 'تړل',
    'submit' => 'سپارل',
    'update' => 'تازه کول',
    'create' => 'جوړول',
    'manage' => 'اداره کول',
    'list' => 'لیست',
    'details' => 'جزئیات',
    'information' => 'معلومات',
    'general' => 'عمومي',
    'advanced' => 'پرمختللي',
    'basic' => 'بنسټیز',
    'all' => 'ټول',
    'today' => 'نن',
    'this_month' => 'دا میاشت',
    'completed' => 'بشپړ شوی',
    'pending' => 'پاتې',
    'active' => 'فعال',
    'inactive' => 'غیر فعال',
    'yes' => 'هو',
    'no' => 'نه',
    'enabled' => 'فعال',
    'disabled' => 'غیر فعال',
    'public' => 'عامه',
    'private' => 'شخصي',
    'system_operations' => 'د سیسټم عملیات',
    'shop_management' => 'د پلورنځي اداره',
    'motorcycle_parts_shop' => 'د موټرسایکل د برخو پلورنځی',

    // Additional translations
    'from_last_month' => 'د تیرې میاشتې څخه',
    'from_last_week' => 'د تیرې اونۍ څخه',
    'from_yesterday' => 'د پرون څخه',
    'overview' => 'عمومي کتنه',
    'performance' => 'فعالیت',
    'latest_activities' => 'وروستي فعالیتونه',
    'activity' => 'فعالیت',
    'amount' => 'مقدار',
    'new_sale' => 'نوې پلورنه',
    'cash' => 'نغدي',
    'available_stock' => 'موجود',
    'select_product' => 'توکی غوره کړئ',
    'add_row' => 'کرښه اضافه کړئ',
    'remove' => 'لرې کړئ',
    'invoice_number' => 'د فاکتور شمیره',
    'supplier_name' => 'د چمتو کوونکي نوم',
    'creation_date' => 'د جوړولو نیټه',
    'operations' => 'عملیات',
    'view_details' => 'جزئیات وګورئ',
    'print_invoice' => 'فاکتور چاپ کړئ',
    'download_pdf' => 'PDF ډاونلوډ کړئ',
    'export' => 'صادرول',
    'import' => 'وارد کول',
    'backup_created' => 'بیک اپ جوړ شو',
    'create_new_backup' => 'نوی بیک اپ جوړ کړئ',
    'system_statistics' => 'د سیسټم احصائیې',
    'general_settings' => 'عمومي تنظیمات',
    'shop_information' => 'د پلورنځي معلومات',
    'system_language' => 'د سیسټم ژبه',
    'date_type' => 'د نیټې ډول',
    'gregorian' => 'میلادي',
    'jalali' => 'لمریز',
    'automatic_backup' => 'اتوماتیک بیک اپ',
    'system_notifications' => 'د سیسټم خبرتیاوې',
    'save_changes' => 'بدلونونه وساتئ',

    // Dashboard specific
    'today_expenses' => 'نن لګښتونه',
    'today_net_profit' => 'نن خالصه ګٹه',
    'quick_actions' => 'چٹک عملیات',
    'quick_sale' => 'چٹک پلورنه',
    'new_product_btn' => 'نوی توکی',
    'new_customer_btn' => 'نوی پیرودونکی',
    'new_purchase_btn' => 'نوی پیرود',
    'expenses_btn' => 'لګښتونه',
    'low_stock_btn' => 'لښ موجود',
    'reports_btn' => 'راپورونه',
    'backup_btn' => 'بیک اپ',
    'weekly_sales_trend' => 'د اونۍ د پلورنې بهیر',
    'daily_sales_last_7_days' => 'د ۷ ورځو ورځنۍ پلورنه',
    'top_5_products' => '۵ غوره توکي',
    'inventory_trend' => 'د موجوداتو بهیر',
    'inventory_status' => 'د موجوداتو حالت',
    'profit_trend' => 'د ګٹې بهیر',
    'daily_profit_last_7_days' => 'د ۷ ورځو ورځنۍ ګٹه',
    'recent_sales' => 'وروستي پلورنې',
    'last_5_invoices' => 'د ۵ وروستيو فاکتورو فهرست',
    'view_all' => 'ٹول وګورئ',
    'cash_customer' => 'نغدي پیرودونکی',
    'print_invoice' => 'فاکتور چاپ کړئ',
    'view_details' => 'جزئیات وګورئ',
    'edit_invoice' => 'فاکتور سمون',

    // More translations
    'code' => 'کوډ',
    'stock' => 'موجود',
    'afghani_currency' => 'افغانۍ',
    'previous' => 'مخکې',
    'next' => 'راتلونکی',
    'current' => 'اوسنی',
    'all_tab' => 'ټول',
    'today_tab' => 'نن',
    'this_month_tab' => 'دا میاشت',
    'invoice' => 'فاکتور',
    'customer_name' => 'د پیرودونکي نوم',
    'total_amount_label' => 'ٹول مقدار',
    'discount_label' => 'تخفیف',
    'final_amount_label' => 'وروستی مقدار',
    'date_label' => 'نیټه',
    'status_label' => 'حالت',
    'actions_label' => 'عملیات',
    'print_invoice_action' => 'فاکتور چاپ کړئ',
    'view_details_action' => 'جزئیات وګورئ',
    'download_pdf_action' => 'PDF ډاونلوډ کړئ',
    'customer_label' => 'پیرودونکی',
    'discount_input' => 'تخفیف',
    'invoice_items_label' => 'د فاکتور توکي',
    'product_label' => 'توکی',
    'quantity_label' => 'مقدار',
    'unit_price_label' => 'د واحد بیه',
    'sum_label' => 'مجموعه',
    'operations_label' => 'عملیات',
    'add_item' => 'ایټم اضافه کړئ',
    'calculator' => 'کیلکولیټر',
    'money_bill' => 'پیسې بل',
    'cancel_button' => 'لغوه کول',
    'submit_invoice_button' => 'فاکتور وسپارئ',

    // Categories
    'category_management' => 'د ډولونو اداره',
    'new_category' => 'نوی ډول',
    'category_name' => 'د ډول نوم',
    'category_description' => 'د ډول تشریح',

    // Customers
    'customer_management' => 'د پیرودونکو اداره',
    'new_customer' => 'نوی پیرودونکی',
    'customer_phone' => 'د پیرودونکي تلیفون',
    'customer_address' => 'د پیرودونکي پته',

    // Suppliers
    'supplier_management' => 'د چمتو کوونکو اداره',
    'new_supplier' => 'نوی چمتو کوونکی',
    'supplier_phone' => 'د چمتو کوونکي تلیفون',
    'supplier_address' => 'د چمتو کوونکي پته',

    // Purchases
    'purchase_invoice' => 'د پیرود فاکتور',
    'purchase_date' => 'د پیرود نیټه',
    'purchase_total' => 'د پیرود ٹول',

    // Reports
    'reports_title' => 'راپورونه',
    'sales_reports' => 'د پلورنې راپورونه',
    'product_reports' => 'د توکو راپورونه',
    'customer_reports' => 'د پیرودونکو راپورونه',

    // Login
    'login_title' => 'سیسټم ته د ننوتلو',
    'username_label' => 'د کاروونکي نوم',
    'password_label' => 'پټ نوم',
    'login_button' => 'ننوتل',
    'remember_me' => 'زه مې سته وساته',

    // Profile
    'profile_title' => 'د کاروونکي پروفایل',
    'change_password' => 'پټ نوم بدلول',
    'current_password' => 'اوسنی پټ نوم',
    'new_password' => 'نوی پټ نوم',
    'confirm_password' => 'د پټ نوم تایید',

    // Common form elements
    'required_field' => 'اړین ډک',
    'optional_field' => 'اختیاري',
    'select_category' => 'ډول غوره کړئ',
    'select_customer' => 'پیرودونکی غوره کړئ',
    'select_supplier' => 'چمتو کوونکی غوره کړئ',
    'list_title' => 'لیست',
    'add_new' => 'نوی اضافه کړئ',
    'edit_item' => 'سمون',
    'delete_item' => 'ړنګول',
    'view_item' => 'کتل',

    // Complete translations for all remaining texts
    'welcome' => 'په راغلاست!',
    'login_with_credentials' => 'د کاروونکي معلوماتو سره ننوتل',
    'or_login_with' => 'یا د کاروونکي معلوماتو سره ننوزئ',
    'forgot_password' => 'پټ نوم هیر شوی؟',
    'about_us' => 'زموږ د اړیکو',
    'blog' => 'بلاګ',
    'licenses' => 'جوازونه',
    'facebook' => 'فیسبوک',
    'google' => 'ګوګل',
    'error_exclamation' => 'تیروتنه!',
    'wrong_credentials' => 'د کاروونکي نوم یا پټ نوم غلط دی',
    'invalid_request' => 'غلط غوښتنه',
    'chart' => 'چارټ',
    'daily_sales' => 'ورځنۍ پلورنه',
    'last_30_days' => '(30 ورځې مخکې)',
    'invoice_count' => 'د فاکتور شمیر',
    'total_sales' => 'ٹول پلورنه',
    'sold_quantity' => 'پلورل شوی مقدار',
    'total_revenue' => 'ٹول عاید',
    'stock_quantity' => 'موجود مقدار',
    'toman' => 'تومان',
    'search_placeholder' => 'لټون...',
    'no_data' => 'معلومات نشته',
    'loading' => 'باریدو',
    'success_operation' => 'عملیات په بریالیتوب سره ترسره شو',
    'operation_error' => 'د عملیاتو په ترسره کولو کې تیروتنه',
    'server_error' => 'د سرور سره د ارتباط کې تیروتنه',
    'confirm_delete_question' => 'ایا تاسو د ړنګولو څخه ډاډه یاست؟',
    'successfully_deleted' => 'په بریالیتوب سره وړنګول شو',
    'delete_error' => 'د ړنګولو کې تیروتنه',
    'add_new_item' => 'نوی ایټم اضافه کړئ',
    'edit_title' => 'سمون',
    'update_button' => 'تازه کول',
    'new_password_optional' => 'نوی پټ نوم (اختیاري)',
    'system_title' => 'د موټرسایکل د برخو پلورنځي مدیریت سیسټم',
    'contact_number' => 'د تماس شمیره',
    'main_street' => 'اصلي سړک',
    'plate_number' => 'پلیټ شمیره',
    'currency_unit' => 'د پیسو واحد',
    'system_language_label' => 'د سیسټم ژبه',
    'persian' => 'فارسي',
    'pashto' => 'پښتو',
    'english' => 'انګلیسي',
    'date_format_label' => 'د نیټې ډول',
    'solar_hijri' => 'لمریز',
    'settings_updated' => 'تنظیمات په بریالیتوب سره تازه شول',
    'settings_update_error' => 'د تنظیماتو د تازه کولو کې تیروتنه'
];
?>